### ISSUE TITLE
Benchmark with ROMA

### ISSUE THREAD

**Issue by serkan-ozal** [arnaudroger/SimpleFlatMapper#216]
Hi, do you have any benchmark with [Spring-JDBC-ROMA](https://github.com/serkan-ozal/spring-jdbc-roma-impl)?

**Comment by arnaudroger** [comment]
I do - not sure it's the right version though -, 
I had a project orm-benchmark with all the benchmark but because of all the dep it's a bit a nightmare will split it up.

It's under Roma. The size of the row might affect the result. I also deliberately avoided date column as it then overwhelmed the benchmark.

https://github.com/arnaudroger/SimpleFlatMapper/wiki/Jdbc-Performance-Local-Mysql
https://github.com/arnaudroger/SimpleFlatMapper/wiki/Jdbc-Performance-In-Memory-HsqlDb

Roma is very close to sfm, the only reason its not clearly faster is because of the name vs index lookup.

**Comment by serkan-ozal** [comment]
Thanks for the detailed information.
Do you now which version of ROMA was used?
3 months ago, I had published the `2.0.0.RELEASE` version.

**Comment by arnaudroger** [comment]
It s not that one I have not changed the version for a while will update and rerun

**Comment by serkan-ozal** [comment]
Ok, thanks

**Comment by arnaudroger** [comment]
see https://github.com/arnaudroger/SimpleFlatMapper/tree/master/sfm-benchmark/sfm-benchmark-jdbc and https://github.com/arnaudroger/SimpleFlatMapper/tree/master/sfm-benchmark/sfm-benchmark-roma

I still need to readd all the benchmarks under them and collect the data

**Comment by arnaudroger** [comment]
new set of benchmark results https://github.com/arnaudroger/mapping-benchmark/tree/master/results/mysql
