### ISSUE TITLE
Support jdk8 parameter names when injecting constructors

### ISSUE THREAD

**Issue by DanielJoyce** [arnaudroger/SimpleFlatMapper#282]
JDK 8 compiler "-parameters" switch supports retaining parameter information for methods and constructurs

https://docs.oracle.com/javase/tutorial/reflect/member/methodparameterreflection.html

http://www.adam-bien.com/roller/abien/entry/named_parameters_in_java_8

**Comment by DanielJoyce** [comment]
Might have to have seperate artifact for jdk8, but its a very powerful feature.

**Comment by arnaudroger** [comment]
We can do that easily java8 specific code is already isolated. I add a look a bit of time ago and because the compiler option is disabled by default I guessed that the information would rarely be available. 
I don't know of anybody who have that flag on or even knows about the flag ;) but sure it's possible
