### ISSUE TITLE
Support LazyCrud in JdbcTemplateCrudDSL

### ISSUE THREAD

**Issue by Infeligo** [arnaudroger/SimpleFlatMapper#439]
`CrudDSL` allows building either `DefaultCrud` or `LazyCrud`. The latter has the advantage of not requiring a connection on `Crud` instantiation, which comes for the cost of the first query being slower.

However, when creating a `JdbcTemplateCrud` instance (which uses `Crud` underneath) via `JdbcTemplateCrudDSL`, there is no such option – it wants a connection immediately in all cases. It would be nice if `JdbcTemplateCrudDSL` abilities would be consistent with `CrudDSL`.

**Comment by arnaudroger** [comment]
so just trying to understand, the JdbcTemplateCrud needs a jdbcTemplate as it is just a wrapper around the crud that uses connection callback. would you then pass the jdbcTemplate at execution time?
instead of doing create(value), you would do create(value, jdbcTemplate) 

or is it because you don't want the JdbcTenplateCrud to open a connection on the initialization cycle? If so I would be interested in understanding why?

either way, it would not be very difficult.

**Comment by Infeligo** [comment]
I want this feature for the second reason (and also for the sake of uniformity). The simplest example is the use of Spring Boot's [database initialization](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html#howto-initialize-a-database-using-spring-jdbc). Tables are created _after_ all beans have been instantiated and this will cause a problem.

**Comment by arnaudroger** [comment]
I see makes sense.
would a new lazilyTo method do? like

```
JdbcTemplateCrud<DbObject, Long> objectCrud =
				JdbcTemplateMapperFactory.newInstance()
						.<DbObject, Long>crud(DbObject.class, Long.class)
						.lazilyTo(template, "TEST_DB_OBJECT_LAZY");
```

**Comment by arnaudroger** [comment]
Just pushed 3.11.8 to maven central with the lazilyTo method can you check it out?
