### ISSUE TITLE
Ability to require specified CSV columns

### ISSUE THREAD

**Issue by clamothe** [arnaudroger/SimpleFlatMapper#518]
It would be nice to be able to validate that all expected columns are present in the CSV.

`ignorePropertyNotFound` fulfills my desire to allow the CSV to contain additional unspecified columns. However, there is no MapperBuilderErrorHandler method called if a defined column is actually missing from the CSV.

I've tried adding all required headers using `CsvMapperFactory.addKeys`.

**Comment by arnaudroger** [comment]
keys are there for join, the mapper does not require anything to be present at the minute.
it should be might be possible to had a flag on the property to say it's mandatory and fail to build the mapper if that the case. that would look like that.
but the problem is that column name don't have to match exactly the prop name
anyway i'll looked into it.
prob something like

```java
CsvMapperFactory.newInstance().addColumnProperty("foo", MandatoryProperty.INSTANCE);
```

**Comment by clamothe** [comment]
Thanks for your reply. It's worth noting that I have solved this by adding `@NotNull` annotations to each of my fields, then running Hibernate Validator.
